#!/usr/bin/env python

'''
This script returns all or specified facts about your Mac.

Requirements
------------
+ OS X 10.9.x
+ python 2.7

'''

##############################################################################
# Copyright 2014 Joseph Chilcote
# 
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy
#  of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
##############################################################################

import os
import re
import sys
import socket
import platform
import sysconfig
import subprocess
import argparse
import plistlib
from urllib import urlopen
import json
from collections import Counter
from AppKit import NSScreen
from CoreFoundation import CFPreferencesCopyAppValue
from SystemConfiguration import *
import objc

objc.loadBundle('CoreWLAN',
                bundle_path='/System/Library/Frameworks/CoreWLAN.framework',
                module_globals=globals())

class Facts(object):
    '''
    Facts object
    Import the module into your python script:

    from pyfacts import Facts

    fact = Facts()
    serial = fact.get_serial()
    print serial
    '''

    def __init__(self, all=False):
        self.facts = {}
        self.prefs = SCPreferencesCreate(None, 'foo', None)
        self.network_services = SCNetworkServiceCopyAll(self.prefs)
        self.network_interfaces = SCNetworkInterfaceCopyAll()
        self.wifi = CWInterface.interfaceNames()
        self.activenetwork = self.get_activenetwork()
        if self.wifi:
            for iname in self.wifi:
                self.interface = CWInterface.interfaceWithName_(iname)
        if all:
            self.get_all()

    def get_all(self):
        '''Returns all facts for interactive mode'''
        self.facts['script'] = self.get_script()
        self.facts['hostname'] = self.get_hostname()
        self.facts['kernelversion'] = self.get_kernelversion()
        self.facts['productversion'] = self.get_productversion()
        self.facts['productversionmajor'] = self.get_productversionmajor()
        self.facts['productversionminor'] = self.get_productversionminor()
        self.facts['pythonversion'] = self.get_pythonversion()
        self.facts['architecture'] = self.get_architecture()
        self.facts['processor'] = self.get_processor()
        self.facts['platform'] = self.get_platform()
        self.facts['id'] = self.get_id()
        self.facts['user'] = self.get_user()
        self.facts['uname'] = self.get_uname()
        self.facts['sysinfo'] = self.get_sysinfo()
        self.facts['homedir'] = self.get_homedir()
        self.facts['prompt'] = self.get_prompt()
        self.facts['path'] = self.get_path()
        self.facts['term'] = self.get_term()
        self.facts['term_program'] = self.get_termprogram()
        self.facts['shell'] = self.get_shell()
        self.facts['python_interpreter'] = self.get_pythoninterpreter()
        self.facts['editor'] = self.get_editor()
        self.facts['pwd'] = self.get_pwd()
        self.facts['tmpdir'] = self.get_tmpdir()
        self.facts['cwd'] = self.get_cwd()
        self.facts['euid'] = self.get_euid()
        self.facts['uid'] = self.get_uid()
        self.facts['egid'] = self.get_egid()
        self.facts['gid'] = self.get_gid()
        self.facts['groups'] = self.get_groups()
        self.facts['ip'] = self.get_ip()
        self.facts['external_ip'] = self.get_external_ip()
        self.facts['networkinterfaces'] = self.get_networkinterfacelist()
        self.facts['networkservices'] = self.get_networkservices()
        self.facts['searchdomains'] = self.get_searchdomains()
        self.facts['dnsservers'] = self.get_dnsservers()
        self.facts['wifiinterface'] = self.get_wifiinterface()
        self.facts['macaddress'] = self.get_macaddress()
        self.facts['model'] = self.get_model()
        self.facts['memory'] = self.get_memory()
        self.facts['buildversion'] = self.get_buildversion()
        self.facts['cpucores'] = self.get_cpucores()
        self.facts['cpus'] = self.get_cpus()
        self.facts['uuid'] = self.get_uuid()
        self.facts['serial'] = self.get_serial()
        self.facts['ssid'] = self.get_ssid()
        self.facts['wifistatus'] = self.get_wifistatus()
        self.facts['wifimacaddress'] = self.get_wifimacaddress()
        self.facts['activenetwork'] = self.get_activenetwork()
        self.facts['activepower'] = self.get_activepower()
        self.facts['batterycycles'] = self.get_batterycycles()
        self.facts['batteryhealth'] = self.get_batteryhealth()
        self.facts['batteryserial'] = self.get_batteryserial()
        self.facts['screenresolution'] = self.get_screenresolution()
        self.facts['sus'] = self.get_sus()
        self.facts['freespace'] = self.get_freespace()
        self.facts['bootcamp'] = self.get_bootcamp()
        self.facts['filevaultstatus'] = self.get_filevalutstatus()
        self.facts['gatekeeperstatus'] = self.get_gatekeeperstatus()
        self.facts['javaversion'] = self.get_javaversion()
        self.facts['remotelogin'] = self.get_remotelogin()
        self.facts['is_virtual'] = self.get_is_virtual()
        self.facts['board-id'] = self.get_board_id()
        self.facts['is_64-bit_capable'] = self.get_is_64()
        self.facts['firmware_version'] = self.get_firmware_version()
        self.facts['cidr'] = self.get_cidr()
        self.facts['bootvolume'] = self.get_bootvolume()
        self.facts['recoveryhd'] = self.get_recoveryhd()
        self.facts['volumeuuid'] = self.get_volumeuuid()

    def get_script(self):
        '''Returns the name of this script'''
        try:
            return sys.argv[0]
        except:
            return None
    
    def get_hostname(self):
        '''Returns the hostname of this Mac
        if it is not a FQDN, we will append .local'''
        # hostname = platform.node()
        ## Using SystemConfiguration:
        # hostname = SCDynamicStoreCopyComputerName(None, None)[0]
        # hostname = SCDynamicStoreCopyLocalHostName(None)
        try:
            hostname = socket.gethostname()
            if not '.' in hostname:
                return hostname + '.local'
            return hostname
        except:
            return None

    def get_kernelversion(self):
        '''Returns the darwin version of this Mac
        example: 13.1.0'''
        try:
            return platform.release()
        except:
            return None

    def get_productversion(self):
        '''Returns the os x version of this Mac
        example: 10.9.2'''
        try:
            return platform.mac_ver()[0]
        except:
            return None

    def get_productversionmajor(self):
        '''Returns the major os x version of this Mac'''
        try:
            return '.'.join(platform.mac_ver()[0].split('.')[0:2])
        except:
            return None

    def get_productversionminor(self):
        '''Returns the minor os x version of this Mac'''
        try:
            return platform.mac_ver()[0].split('.')[-1]
        except:
            return None

    def get_pythonversion(self):
        '''Returns the python version on this Mac'''
        try:
            return platform.python_version()
        except:
            return None

    def get_architecture(self):
        '''Returns the architecture of this Mac
        example: x86_64'''
        try:
            return platform.machine()
        except:
            return None

    def get_platform(self):
        '''Returns the processor type of this Mac
        exxample: darwin'''
        try:
            return sys.platform
        except:
            return None

    def get_id(self):
        '''Returns the current console user on this Mac'''
        try:
            return os.getlogin()
        except:
            return None
        ## Using SystemConfiguration:
        # return SCDynamicStoreCopyConsoleUser(None, None, None)[0]

    def get_user(self):
        script = ['/usr/bin/last']
        users = []
        get_last = subprocess.check_output(script)
        for line in get_last.splitlines():
            if line != '':
                name = line.split()
                users.append(name[0])
        users = Counter(users).most_common()
        return users[0][0]

    def get_uname(self):
        '''Returns the full uname of this Mac as a tuple'''
        try:
            return os.uname()
        except:
            return none

    def get_sysinfo(self):
        '''Returns the system info of this Mac'''
        try:
            return os.uname()[3]
        except:
            return None

    def get_homedir(self):
        '''Returns the home directory of the current user'''
        try:
            return os.environ['HOME']
        except:
            return None

    def get_prompt(self):
        '''Returns the prompt env of the current user'''
        try:
            return os.environ['PROMPT_COMMAND']
        except:
            return None

    def get_path(self):
        '''Returns the path env of the current user'''
        try:
            return os.environ['PATH']
        except:
            return None

    def get_term(self):
        '''Returns the term env of the current user'''
        try:
            return os.environ['TERM']
        except:
            return None

    def get_termprogram(self):
        '''Returns the term program env of the current user'''
        try:
            return os.environ['TERM_PROGRAM']
        except:
            return None

    def get_shell(self):
        '''Returns the shell env of the current user'''
        try:
            return os.environ['SHELL']
        except:
            return None

    def get_pythoninterpreter(self):
        '''Returns the python interpreter on this Mac'''
        return os.environ['VERSIONER_PYTHON_VERSION']

    def get_editor(self):
        '''Returns the editor env of the current user'''
        try:
            return os.environ['EDITOR']
        except:
            return None

    def get_pwd(self):
        '''Returns the pwd'''
        try:
            return os.environ['PWD']
        except:
            return None

    def get_tmpdir(self):
        '''Returns the tempdir env of the current user'''
        try:
            return os.environ['TMPDIR']
        except:
            return None

    def get_cwd(self):
        '''Returns the cwd'''
        try:
            return os.getcwd()
        except:
            return None

    def get_euid(self):
        '''Returns the euid of the current user'''
        try:
            return os.geteuid()
        except:
            return None

    def get_uid(self):
        '''Returns the uid of the current user'''
        ## Using SystemConfiguration:
        # return SCDynamicStoreCopyConsoleUser(None, None, None)[1]
        try:
            return os.getuid()
        except:
            return None

    def get_egid(self):
        '''Returns the egid of the current user'''
        try:
            return os.getegid()
        except:
            return None

    def get_gid(self):
        '''Returns the gid of the current user'''
        ## Using SystemConfiguration:
        # return SCDynamicStoreCopyConsoleUser(None, None, None)[2]
        try:
            return os.getgid()
        except:
            return None

    def get_groups(self):
        '''Returns the groups of the current user'''
        try:
            return os.getgroups()
        except:
            return None

    def get_ip(self):
        '''Returns the IP address of the Mac'''
        hostname = self.get_hostname()
        try:
            return socket.gethostbyname(hostname)
        except:
            return None

    def get_external_ip(self):
        url = 'http://api.hostip.info/get_json.php'
        try:
            info = json.loads(urlopen(url).read().decode('utf-8'))
            return info['ip']
        except IOError as err:
            return 'Cannot connect to %s: %s' % (url, err)

    def get_networkservices(self):
        '''Returns a list of all network interface names'''
        l = []
        for service in self.network_services:
            l.append(SCNetworkServiceGetName(service))
        return l
    
    def get_searchdomains(self):
        '''Returns a list of search domains'''
        interfaces = self.get_networkservices()
        d = {}
        for interface in interfaces:
            if 'Ethernet' in interface or 'Wi-Fi' in interface:
                cmd = ['/usr/sbin/networksetup', '-getsearchdomains',
                        interface]
                output = subprocess.check_output(cmd)
                l = []
                for domain in output.splitlines():
                    if not 'There aren\'t' in domain:
                        l.append(domain)
                d[interface] = l
        return d

    def get_dnsservers(self):
        '''Returns a list of search domains'''
        interfaces = self.get_networkservices()
        d = {}
        for interface in interfaces:
            if 'Ethernet' in interface or 'Wi-Fi' in interface:
                cmd = ['/usr/sbin/networksetup', '-getdnsservers',
                        interface]
                output = subprocess.check_output(cmd)
                l = []
                for domain in output.splitlines():
                    if not 'There aren\'t' in domain:
                        l.append(domain)
                d[interface] = l
        return d

    def get_networkinterfacelist(self):
        '''Returns a list of all network interface names'''
        d = {}
        for interface in self.network_interfaces:
            d[SCNetworkInterfaceGetLocalizedDisplayName(interface)] = (
                SCNetworkInterfaceGetBSDName(interface),
                SCNetworkInterfaceGetHardwareAddressString(interface)
                )
        return d

    def get_wifiinterface(self):
        '''Returns the name of the Wi-Fi network interface'''
        interface = self.get_networkinterfacelist()
        try:
            return interface['Wi-Fi'][0]
        except KeyError:
            return None

    def get_wifimacaddress(self):
        '''Returns the MAC address of the Wi-Fi network interface'''
        interface = self.get_networkinterfacelist()
        try:
            return interface['Wi-Fi'][1]
        except KeyError:
            return None

    def get_wifistatus(self):
        '''Returns the wifi status
        Yes or No'''
        try:
            if self.interface.powerOn() == 1:
                return "Yes"
            return "No"
        except AttributeError:
            return None

    def get_ssid(self):
        '''Returns the SSID of the Wi-Fi interface'''
        try:
            return self.interface.ssid()
        except AttributeError:
            return None

    def get_serial(self):
        '''Returns the serial number of the Mac'''
        output = subprocess.check_output(['/usr/sbin/ioreg', '-c',
                                        'IOPlatformExpertDevice', '-d', '2'])
        for line in output.splitlines():
            if 'IOPlatformSerialNumber' in line:
                return line.split(' = ')[1].replace('\"','')
        return None

    def get_activepower(self):
        '''Returns the active power source
        Battey or AC'''
        output = subprocess.check_output(['/usr/bin/pmset', '-g'])
        for line in output.splitlines():
            if '*' in line:
                return line.split(' ')[0]

    def get_batterycycles(self):
        '''Returns the number of battery cycles'''
        output = subprocess.check_output(['/usr/sbin/ioreg', '-r', '-c',
                                         'AppleSmartBattery'])
        for line in output.splitlines():
            if 'CycleCount' in line:
                return line.split(' = ')[1]

    def get_batteryhealth(self):
        '''Returns the battery health
        Healthy or Failing'''
        output = subprocess.check_output(['/usr/sbin/ioreg', '-r', '-c',
                                        'AppleSmartBattery'])
        for line in output.splitlines():
            if 'PermanentFailureStatus' in line:
                try:
                    if int(line.split(' = ')[1]) == 0:
                        return 'Healthy'
                    return 'Failing'
                except ValueError:
                    return None

    def get_batteryserial(self):
        '''Returns the serial of the battery'''
        output = subprocess.check_output(['/usr/sbin/ioreg', '-r', '-c',
                                                'AppleSmartBattery'])
        for line in output.splitlines():
            if 'BatterySerialNumber' in line:
                try:
                    return line.split(' = ')[1].replace('\"','')
                except IndexError:
                    return None

    def get_freespace(self):
        '''Returns the free space on the boot drive'''
        output = subprocess.check_output(['/usr/sbin/diskutil', 'info', 
                                        '-plist', '/'])
        xml = plistlib.readPlistFromString(output)
        return int(xml['FreeSpace']) / 1000 / 1000 / 1000

    def get_bootcamp(self):
        '''Returns whether a bootcamp volume is detected'''
        output = subprocess.check_output(['/usr/sbin/diskutil', 'list'])
        for line in output.splitlines():
            if 'Microsoft Basic Data' in line:
                return 'Yes'
            return 'No'

    def get_filevalutstatus(self):
        '''Returns whether filevault is enabled'''
        output = subprocess.check_output(['/usr/bin/fdesetup', 'status'])
        return output.strip()

    def get_gatekeeperstatus(self):
        '''Returns whether gatekeeper is enabled'''
        output = subprocess.check_output(['/usr/sbin/spctl', '--status'])
        return output.strip()

    def get_activenetwork(self):
        '''Returns the active network interface of the Mac'''
        output = subprocess.check_output(['/usr/sbin/netstat', '-rn'])
        for line in output.splitlines():
            if 'default' in line and not 'utun' in line:
                return line.split('     ')[-1].strip()

    def get_macaddress(self):
        '''Returns the MAC address of the current active network'''
        interface = self.activenetwork
        output = subprocess.check_output(['/usr/sbin/networksetup',
                                        '-getmacaddress', interface])
        return output.split(' ')[2]

    def get_model(self):
        '''Returns the hardware model of the Mac'''
        output = subprocess.check_output(['/usr/sbin/sysctl', '-n',
                                            'hw.model'])
        return output.strip()

    def get_memory(self):
        '''Returns the memory in bytes of the Mac'''
        output = subprocess.check_output(['/usr/sbin/sysctl', '-n',
                                            'hw.memsize'])
        return int(output.strip())/1024/1024/1024

    def get_processor(self):
        '''Returns the processor model of the Mac'''
        output = subprocess.check_output(['/usr/sbin/sysctl', '-n',
                                        'machdep.cpu.brand_string'])
        return output.strip()

    def get_is_64(self):
        '''Returns whether the Mac is 64-bit capable'''
        output = subprocess.check_output(['/usr/sbin/sysctl', '-n',
                                        'hw.cpu64bit_capable'])
        if output:
            return True
        return False

    def get_buildversion(self):
        '''Returns the os build version of the Mac'''
        output = subprocess.check_output(['/usr/sbin/sysctl', '-n',
                                        'kern.osversion'])
        return output.strip()
    
    def get_cpucores(self):
        '''Returns how many CPU cores on the Mac'''
        output = subprocess.check_output(['/usr/sbin/sysctl', '-n', 'hw.ncpu'])
        return output.strip()

    def get_cpus(self):
        '''Returns how many CPUs on the Mac'''
        output = subprocess.check_output(['/usr/sbin/sysctl', '-n',
                                        'hw.physicalcpu'])
        return output.strip()

    def get_uuid(self):
        '''Returns the UUID of the Mac'''
        output = subprocess.check_output(['/usr/sbin/sysctl', '-n',
                                        'kern.uuid'])
        return output.strip()

    def get_screenresolution(self):
        '''Returns the screen resolution of the main screen'''
        width = NSScreen.mainScreen().frame().size.width
        height = NSScreen.mainScreen().frame().size.height
        return width, height

    def get_sus(self):
        '''Returns the custom SUS if set'''
        sus = CFPreferencesCopyAppValue('CatalogURL',
                        '/Library/Preferences/com.apple.SoftwareUpdate.plist')
        if not sus:
            return None
        return sus

    def get_javaversion(self):
        '''Returns the java version on this Mac'''
        cmd = "java -version 2>&1 | /usr/bin/awk '/version/{print $3}'"
        task = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                                    stderr=subprocess.PIPE,
                                    shell = True)
        (stdout, stderr) = task.communicate()
        try:
            return re.split('[\s"]+',stdout.strip())[1]
        except IndexError:
            return None

    def get_remotelogin(self):
        '''Returns whether remote login is activated'''
        if os.geteuid() == 0:
            output = subprocess.check_output(['/usr/sbin/systemsetup',
                                            'getremotelogin'])
            return output.split(': ')[1].strip()
        return "run as root to check this setting"

    def get_is_virtual(self):
        '''Returns whether the Mac is a virtual machine'''
        output = subprocess.check_output(['/usr/sbin/sysctl', '-n',
                                            'machdep.cpu.features'])
        if 'VMM' in output:
            return True
        return False

    def get_board_id(self):
        '''Returns the board-id of the Mac
        Ref: https://github.com/hjuutilainen/adminscripts/blob/master/check-mavericks-compatibility.py'''
        output = subprocess.check_output(['/usr/sbin/ioreg', '-p',
                                'IODeviceTree', '-r', '-n', '/', '-d', '1'])
        for line in output.splitlines():
            if 'board-id' in line:
                return re.sub(r"^\s*\"board-id\" = <\"(.*)\">$", r"\1", line)

    def get_firmware_version(self):
        '''Returns a dict of the firmware version of the Mac
        Ref: https://github.com/hjuutilainen/adminscripts/blob/master/check-mavericks-compatibility.py'''
        d = {}
        output = subprocess.check_output(['/usr/sbin/ioreg', '-p', 'IOService',
                '-n', 'AppleAHCIDiskDriver',
                '-r',
                '-l',
                '-d', '1',
                '-w', '0'])
        disk_dict = {}
        for line in output.splitlines():
            m = re.match(r"^\s*\"(?P<key>.*)\" = \"(?P<value>.*)\"$", line)
            if m:
                disk_dict[m.group('key')] = m.group('value').strip()
        model = disk_dict.get('Model', '')
        revision = disk_dict.get('Revision', '')
        return model, revision

    def get_cidr(self):
        '''Returns the cidr of the current network'''
        netmask = ''
        ip = self.get_ip()
        output = subprocess.check_output(['/sbin/ifconfig', 'en0'])
        for line in output.splitlines():
            if ip in line:
                netmask = line.split(' ')[3].lower()
        count = int(0)
        count+=int(netmask.count('f')) * 4
        count+=int(netmask.count('e')) * 3
        count+=int(netmask.count('c')) * 2
        count+=int(netmask.count('8')) * 1
        return '%s.%s/%s' % ('.'.join(ip.split('.')[0:3]), '0', count)

    def get_bootvolume(self):
        '''Returns the boot volume name'''
        output = subprocess.check_output(['/usr/sbin/diskutil', 'info', 
                                        '-plist', '/'])
        xml = plistlib.readPlistFromString(output)
        return xml['MediaName']

    def get_recoveryhd(self):
        '''Returns the recovery hd device name'''
        output = subprocess.check_output(['/usr/sbin/diskutil', 'info', 
                                        '-plist', '/'])
        xml = plistlib.readPlistFromString(output)
        return xml['RecoveryDeviceIdentifier']

    def get_volumeuuid(self):
        '''Returns the boot volume uuid'''
        output = subprocess.check_output(['/usr/sbin/diskutil', 'info', 
                                        '-plist', '/'])
        xml = plistlib.readPlistFromString(output)
        return xml['VolumeUUID']

    def get(self, key):
        '''Returns a single fact for interactive mode'''
        try:
            return self.facts[key]
        except KeyError:
            print 'Error: key not found'
            sys.exit(1)

    def show_all(self):
        '''Returns all facts for interactive mode'''
        try:
            for k, v in sorted(self.facts.items()):
                print "%s: %s" % (k, v)
        except KeyError:
            print "Error: %s" % KeyError

    def list_all(self):
        '''Lists all fact categories for interactive mode'''
        try:
            for k, v in sorted(self.facts.items()):
                print "%s" % k
        except KeyError:
            print "Error: %s" % KeyError

def main():
    '''Runs in interactive mode'''
    parser = argparse.ArgumentParser()
    parser.add_argument('-l', '--list', help='list categories',
                        action='store_true')
    parser.add_argument('category', help='input category',
                        nargs=argparse.REMAINDER)
    
    args = parser.parse_args()

    facts = Facts(all=True)
    # facts = Facts()

    if args.list:
        facts.list_all()
        sys.exit(0)
    if args.category:
        print facts.get(args.category[0])
    else:
        facts.show_all()

if __name__ == "__main__":
    main()